package swd.project.swdgr3project.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import jakarta.persistence.*; // Import JPA annotations
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity class representing a product category in the system.
 */
@Data
@Entity // Tells Hibernate this is a table in the database
@Table(name = "product_categories") // Specifies the table name
public class ProductCategory {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates the ID
    private Long id;

    @Column(nullable = false, unique = true)
    private String name;

    private String description;

    private String imageUrl;

    private boolean active = true;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    // This defines the relationship: One Category has Many Products.
    // 'mappedBy = "category"' is crucial: it tells Hibernate the 'Product' entity owns this relationship.
    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY)
    @ToString.Exclude // Exclude from toString to prevent infinite loops
    @EqualsAndHashCode.Exclude // Exclude from equals/hashCode
    private Set<Product> products = new HashSet<>();

    // Constructors, Getters/Setters, and helper methods are generated by Lombok
    // or are already correct.
}